import type { PublicContent, SiteContent } from '../types.js'

export const defaultSiteContent: SiteContent = {
  brandName: 'ครกหินไทย',
  heroTitle: 'ครกหินแกรนิตแท้\nงานฝีมือไทย',
  heroSubtitle: 'คัดสรรหินคุณภาพดี ผลิตด้วยฝีมือช่างชำนาญ\nทนทานใช้ได้ตลอดชีพ ส่งฟรีทั่วไทย',
  heroImageUrl: '/mortar.svg',
  primaryCtaLabel: 'ดูสินค้าทั้งหมด',
  secondaryCtaLabel: 'สอบถามเพิ่มเติม',
  featuresTitle: 'ทำไมต้องเลือกเรา',
  productsTitle: 'สินค้าของเรา',
  productsSubtitle: 'ครกหินคุณภาพดี ราคาโรงงาน',
  testimonialsTitle: 'ลูกค้าพูดถึงเรา',
  ctaTitle: 'พร้อมสั่งซื้อครกหินคุณภาพดีแล้วหรือยัง?',
  ctaSubtitle: 'โปรโมชั่นพิเศษ! ส่งฟรีทั่วไทยเมื่อสั่งซื้อครบ 1,000 บาท',
  ctaButtonLabel: 'สั่งซื้อเลย',
  contactTitle: 'ติดต่อเรา',
  phone: '081-784-1857',
  lineId: '@pesilathong',
  email: 'pongpat.w@hotmail.com',
  address: '12 หมู่ 10 ต.พิชัย อ.เมือง จ.ลำปาง 52000',
  footerDescription: 'ผู้ผลิตและจำหน่ายครกหินคุณภาพดี ส่งตรงจากโรงงานถึงบ้านคุณ',
}

export const defaultContent: PublicContent = {
  siteContent: defaultSiteContent,
  stats: [
    { id: 1, value: '30+', label: 'ปีประสบการณ์', sortOrder: 1 },
    { id: 2, value: '10,000+', label: 'ลูกค้าพึงพอใจ', sortOrder: 2 },
    { id: 3, value: '100%', label: 'หินแท้ธรรมชาติ', sortOrder: 3 },
  ],
  features: [
    {
      id: 1,
      icon: '🏔️',
      title: 'หินแกรนิตแท้',
      description: 'คัดสรรหินคุณภาพดีจากแหล่งธรรมชาติ',
      sortOrder: 1,
    },
    {
      id: 2,
      icon: '🔨',
      title: 'ฝีมือช่างชำนาญ',
      description: 'ผลิตโดยช่างฝีมือที่มีประสบการณ์กว่า 30 ปี',
      sortOrder: 2,
    },
    {
      id: 3,
      icon: '✨',
      title: 'ทนทานใช้ได้นาน',
      description: 'รับประกันคุณภาพ ใช้งานได้ตลอดชีพ',
      sortOrder: 3,
    },
    {
      id: 4,
      icon: '🚚',
      title: 'จัดส่งทั่วไทย',
      description: 'บริการส่งฟรีทั่วประเทศ เมื่อซื้อครบ 1,000 บาท',
      sortOrder: 4,
    },
  ],
  products: [
    {
      id: 1,
      name: 'ครกหินแกรนิต ขนาดเล็ก',
      sizeLabel: '5 นิ้ว',
      price: 450,
      originalPrice: 590,
      imageUrl: '/mortar.svg',
      description: 'ครกหินแกรนิตแท้ เนื้อละเอียด ทนทาน เหมาะสำหรับบ้านเรือน',
      inStock: true,
      sortOrder: 1,
    },
    {
      id: 2,
      name: 'ครกหินแกรนิต ขนาดกลาง',
      sizeLabel: '7 นิ้ว',
      price: 690,
      originalPrice: 850,
      imageUrl: '/mortar.svg',
      description: 'ครกหินแกรนิตคุณภาพสูง ขนาดพอดี ใช้งานได้หลากหลาย',
      inStock: true,
      sortOrder: 2,
    },
    {
      id: 3,
      name: 'ครกหินแกรนิต ขนาดใหญ่',
      sizeLabel: '9 นิ้ว',
      price: 990,
      originalPrice: 1200,
      imageUrl: '/mortar.svg',
      description: 'ครกหินแกรนิตขนาดใหญ่ เหมาะสำหรับร้านอาหารหรือครอบครัวใหญ่',
      inStock: true,
      sortOrder: 3,
    },
    {
      id: 4,
      name: 'ครกหินอ่างศิลา พรีเมียม',
      sizeLabel: '8 นิ้ว',
      price: 1490,
      originalPrice: 1800,
      imageUrl: '/mortar.svg',
      description: 'ครกหินอ่างศิลาแท้ 100% งานฝีมือช่างชำนาญ ของดีเมืองชล',
      inStock: false,
      sortOrder: 4,
    },
  ],
  testimonials: [
    {
      id: 1,
      customerName: 'คุณสมศรี',
      location: 'กรุงเทพฯ',
      comment: 'ครกสวยมากค่ะ คุณภาพดีเกินราคา ใช้ตำน้ำพริกอร่อยมาก',
      rating: 5,
      sortOrder: 1,
    },
    {
      id: 2,
      customerName: 'คุณประยุทธ์',
      location: 'เชียงใหม่',
      comment: 'สั่งซื้อมาหลายใบแล้ว ของดีจริงๆ แนะนำเลยครับ',
      rating: 5,
      sortOrder: 2,
    },
    {
      id: 3,
      customerName: 'คุณมาลี',
      location: 'ขอนแก่น',
      comment: 'ส่งเร็วมาก แพ็คอย่างดี ครกสวยถูกใจมากค่ะ',
      rating: 5,
      sortOrder: 3,
    },
  ],
  socialLinks: [
    { id: 1, label: 'Facebook', url: '#', icon: '📘', sortOrder: 1 },
    { id: 2, label: 'Instagram', url: '#', icon: '📸', sortOrder: 2 },
    { id: 3, label: 'TikTok', url: '#', icon: '🎵', sortOrder: 3 },
  ],
}
